# Generated by Django 5.1.3 on 2024-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.TextField(default='Untitled', max_length=225),
        ),
    ]
